options:
  formatter: stylish
  merge-default-rules: false
rules:
  class-name-format: 0
  final-newline: 2
  function-name-format: 0
  id-name-format: 0
  indentation:
    - 2
    - size: tab
  leading-zero: 2
  mixin-name-format: 0
  nesting-depth: 0
  no-color-literals: 0
  no-css-comments: 0
  no-duplicate-properties:
    - 2
    - exclude:
        - background
        - border
        - border-left
        - border-right
        - border-top
        - border-bottom
        - cursor
        - list-style-type
  no-empty-rulesets: 2
  no-ids: 0
  no-important: 0
  no-misspelled-properties:
      - 2
      -
          'extra-properties':
              - 'overflow-scrolling'
  no-url-protocols: 1
  no-trailing-whitespace: 2
  placeholder-name-format: 0
  property-sort-order: 2
  quotes:
    - 2
    - style: double
  space-before-bang: 2
  variable-name-format: 0
