exclude:
  - "lib/**"
  - "node_modules/**"
  - "dist/**"
  - "src/plugins/share/sprites/**"
  - "src/plugins/geomap/sprites/**"
  - "wet-boew-dist/**"

linters:
  StringQuotes:
    enabled: true
    style: double_quotes
  Indentation:
    character: tab
    width: 1
  Comment:
    enabled: false
  LeadingZero:
    enabled: false
  SelectorDepth:
    enabled: false
  PropertySortOrder:
    exclude:
      # Ignore because of greyscale hack
      - "src/plugins/tabs/_base.scss"
  CapitalizationInSelector:
    exclude:
      - "src/plugins/charts/_base.scss"
      - "src/plugins/geomap/_base.scss"
      - "src/plugins/geomap/_ie8.scss"
      - "src/plugins/geomap/_print.scss"
      - "src/plugins/tables/_base.scss"
      - "src/plugins/tables/_ie8.scss"
      - "src/plugins/tables/_screen-sm-max.scss"
      - "src/plugins/tables/_screen-xs-min.scss"
      - "src/plugins/tables/_screen-xxs-max.scss"
      - "src/polyfills/meter/meter.scss"
      - "src/polyfills/meter/demo/meter.scss"
      - "src/polyfills/progress/demo/progress.scss"
  NameFormat:
    enabled: false
  UrlFormat:
    enabled: false
  DuplicateProperty:
    # This unfortunately catches RGB fallbacks
    exclude:
      - "src/plugins/tabs/_base.scss"
      - "src/polyfills/slider/slider.scss"
      - "theme/banner/_base.scss"
  ColorVariable:
    enabled: false
  IdSelector:
    enabled: false
  ImportantRule:
    enabled: false
  NestingDepth:
    enabled: false
  SelectorFormat:
    exclude:
      - "src/plugins/geomap/*.scss"
      - "src/plugins/tables/*.scss"
      - "src/polyfills/meter/*.scss"
      - "src/plugins/charts/_base.scss"
      - "src/plugins/multimedia/_base.scss"
  PropertySortOrder:
    exclude:
      - "src/polyfills/slider/slider.scss"
