#!/usr/bin/perl
# Web Experience Toolkit (WET) / Boîte à outils de l'expérience Web (BOEW)
# www.tbs.gc.ca/ws-nw/wet-boew/terms / www.sct.gc.ca/ws-nw/wet-boew/conditions
$q = $ENV{'QUERY_STRING'};
if ($q =~ s/_e\./_f./gism) {
} elsif ($q =~ s/-eng\./-fra./gism) {
} elsif ($q =~ s/_f\./_e./gism) {
} elsif ($q =~ s/-fra\./-eng./gism) {
}
print "Location: http://" . $ENV{'SERVER_NAME'} . $q . "#tphp\n\n";