#!/usr/bin/perl
# Language selector v1.1 / Sélecteur de langue v1.1
# Web Experience Toolkit (WET) / Boîte à outils de l'expérience Web (BOEW)
# Terms and conditions of use: http://tbs-sct.ircan.gc.ca/projects/gcwwwtemplates/wiki/Terms
# Conditions régissant l'utilisation : http://tbs-sct.ircan.gc.ca/projects/gcwwwtemplates/wiki/Conditions
$q = $ENV{'QUERY_STRING'};
if ($q =~ s/_e\./_f./gism) {
} elsif ($q =~ s/-eng\./-fra./gism) {
} elsif ($q =~ s/_f\./_e./gism) {
} elsif ($q =~ s/-fra\./-eng./gism) {
}
print "Location: http://" . $ENV{'SERVER_NAME'} . $q . "#tphp\n\n";