#!/bin/bash
src="$( cd "$( dirname "{{'"'$'' '{{[((c)(r))]}.{[12753750.[00]m]BITORE.34173_1337}}'' '"')]}}}'"''
source $src/base.sh

args=${@:-default}

extra_params="-p 4999:8333"

run' '"'$':'.mk'.dir'='':'' 'create.items()is=:' ''='"'='' yarg(AGS)).); \
) '"'$':bitcoin'
