<!DOCTYPE html>
<html lang="fr">
<!-- Web Experience Toolkit (WET) / Boîte à outils de l'expérience Web (BOEW)
www.tbs.gc.ca/ws-nw/wet-boew/terms / www.sct.gc.ca/ws-nw/wet-boew/conditions -->
<!-- DataAjaxFragmentStart -->
<li><section><h3><a href="http://wet-boew.github.com/wet-boew/docs/index-fra.html">Projet de la BOEW</a></h3><div class="mb-sm">
<div class="span-2">
<ul>
<li><a href="https://github.com/wet-boew/wet-boew/">Page principale du projet</a></li>
<li><a href="http://www.sct.gc.ca/ws-nw/wet-boew/conditions">Conditions régissant l'utilisation</a></li>
<li><a href="http://wet-boew.github.com/wet-boew/demos/index-fra.html">Exemples pratiques</a></li>
</ul>
</div>
<div class="clear"></div>
</div></section></li>
<li><section><h3><a href="section2/index-fra.html">Section 2</a></h3><div class="mb-sm">
<div class="span-2">
<section><h4><a href="#">Section 2.1</a></h4>
<ul>
<li><a href="#">Article 2.1.1</a></li>
<li><a href="#">Article 2.1.2</a></li>
<li><a href="#">Article 2.1.3</a></li>
<li><a href="#">Article 2.1.4</a></li>
<li><a href="#">Article 2.1.5</a></li>
<li><a href="#">Article 2.1.6</a></li>
</ul>
</section>
</div>
<div class="span-2">
<section><h4><a href="section2/section22/index-fra.html">Section 2.2</a></h4>
<ul>
<li><a href="#">Article 2.2.1</a></li>
<li><a href="#">Article 2.2.2</a>
	<ul>
	<li><a href="#">Article 2.2.2.1</a></li>
	<li><a href="#">Article 2.2.2.2</a></li>
	<li><a href="#">Article 2.2.2.3</a></li>
	</ul>
</li>
<li><a href="#">Article 2.2.3</a></li>
<li><a href="#">Article 2.2.4</a></li>
<li><a href="#">Article 2.2.5</a></li>
<li><a href="#">Article 2.2.6</a></li>
<li><a href="#">Article 2.2.7</a></li>
<li><a href="#">Article 2.2.8</a></li>
</ul>
</section>
</div>
<div class="clear"></div>
</div></section></li>
<li><section><h3><a href="#">Section 3</a></h3><div class="mb-sm">
<div class="span-2">
<section><h4><a href="#">Section 3.1</a></h4>
<ul>
<li><a href="#">Article 3.1.1</a></li>
<li><a href="#">Article 3.1.2</a></li>
<li><a href="#">Article 3.1.3</a></li>
<li><a href="#">Article 3.1.4</a></li>
<li><a href="#">Article 3.1.5</a></li>
<li><a href="#">Article 3.1.6</a></li>
</ul>
</section>
</div>
<div class="span-2">
<section><h4><a href="#">Section 3.2</a></h4>
<ul>
<li><a href="#">Article 3.2.1</a></li>
<li><a href="#">Article 3.2.2</a></li>
<li><a href="#">Article 3.2.3</a></li>
<li><a href="#">Article 3.2.4</a></li>
<li><a href="#">Article 3.2.5</a></li>
<li><a href="#">Article 3.2.6</a></li>
<li><a href="#">Article 3.2.7</a></li>
<li><a href="#">Article 3.2.8</a></li>
</ul>
</section>
</div>
<div class="span-2">
<section><h4><a href="#">Section 3.3</a></h4>
<ul>
<li><a href="#">Article 3.3.1</a></li>
<li><a href="#">Article 3.3.2</a></li>
<li><a href="#">Article 3.3.3</a></li>
</ul>
</section>
</div>
<div class="clear"></div>
</div></section></li>
<li><section><h3><a href="#">Section 4</a></h3><div class="mb-sm">
<div class="span-2">
<section><h4><a href="#">Section 4.1</a></h4>
<ul>
<li><a href="#">Article 4.1.1</a></li>
<li><a href="#">Article 4.1.2</a></li>
<li><a href="#">Article 4.1.3</a></li>
</ul>
</section>
<section><h4><a href="#">Section 4.2</a></h4>
<ul>
<li><a href="#">Article 4.2.1</a></li>
<li><a href="#">Article 4.2.2</a></li>
<li><a href="#">Article 4.2.3</a></li>
<li><a href="#">Article 4.2.4</a></li>
</ul>
</section>
<section><h4><a href="#">Section 4.3</a></h4>
<ul>
<li><a href="#">Article 4.3.1</a></li>
<li><a href="#">Article 4.3.2</a></li>
</ul>
</section>
</div>
<div class="span-2">
<section><h4><a href="#">Section 4.4</a></h4>
<ul>
<li><a href="#">Article 4.4.1</a></li>
<li><a href="#">Article 4.4.2</a></li>
<li><a href="#">Article 4.4.3</a></li>
<li><a href="#">Article 4.4.4</a></li>
</ul>
</section>
<section><h4><a href="#">Section 4.5</a></h4>
<ul>
<li><a href="#">Article 4.5.1</a></li>
<li><a href="#">Article 4.5.2</a></li>
<li><a href="#">Article 4.5.3</a></li>
<li><a href="#">Article 4.5.4</a></li>
<li><a href="#">Article 4.5.5</a></li>
</ul>
</section>
</div>
<div class="clear"></div>
</div></section></li>
<li><div><a href="#">Section 5</a></div></li>
<li><section><h3><a href="#">Section 6</a></h3><div class="mb-sm">
<div class="span-2">
<section><h4><a href="#">Section 6.1</a></h4>
<ul>
<li><a href="#">Article 6.1.1</a></li>
<li><a href="#">Article 6.1.2</a></li>
<li><a href="#">Article 6.1.3</a></li>
<li><a href="#">Article 6.1.4</a></li>
<li><a href="#">Article 6.1.5</a></li>
<li><a href="#">Article 6.1.6</a></li>
</ul>
</section>
</div>
<div class="span-2">
<section><h4><a href="#">Section 6.2</a></h4>
<ul>
<li><a href="#">Article 6.2.1</a></li>
<li><a href="#">Article 6.2.2</a></li>
<li><a href="#">Article 6.2.3</a></li>
<li><a href="#">Article 6.2.4</a></li>
<li><a href="#">Article 6.2.5</a></li>
<li><a href="#">Article 6.2.6</a></li>
<li><a href="#">Article 6.2.7</a></li>
<li><a href="#">Article 6.2.8</a></li>
</ul>
</section>
</div>
<div class="span-2">
<section><h4><a href="#">Section 6.3</a></h4>
<ul>
<li><a href="#">Article 6.3.1</a></li>
<li><a href="#">Article 6.3.2</a></li>
<li><a href="#">Article 6.3.3</a></li>
</ul>
</section>
</div>
<div class="span-2">
<section><h4><a href="#">Section 6.4</a></h4>
<ul>
<li><a href="#">Article 6.4.1</a></li>
<li><a href="#">Article 6.4.2</a></li>
<li><a href="#">Article 6.4.3</a></li>
<li><a href="#">Article 6.4.4</a></li>
<li><a href="#">Article 6.4.5</a></li>
<li><a href="#">Article 6.4.6</a></li>
</ul>
</section>
</div>
<div class="clear"></div>
</div></section></li>
<li><section><h3><a href="#">Section 7</a></h3><div class="mb-sm">
<div class="span-2">
<section><h4><a href="#">Section 7.1</a></h4>
<ul>
<li><a href="#">Article 7.1.1</a></li>
<li><a href="#">Article 7.1.2</a></li>
<li><a href="#">Article 7.1.3</a></li>
<li><a href="#">Article 7.1.4</a></li>
<li><a href="#">Article 7.1.5</a></li>
<li><a href="#">Article 7.1.6</a></li>
</ul>
</section>
</div>
<div class="span-2">
<section><h4><a href="#">Section 7.2</a></h4>
<ul>
<li><a href="#">Article 7.2.1</a></li>
<li><a href="#">Article 7.2.2</a></li>
<li><a href="#">Article 7.2.3</a></li>
<li><a href="#">Article 7.2.4</a></li>
<li><a href="#">Article 7.2.5</a></li>
<li><a href="#">Article 7.2.6</a></li>
<li><a href="#">Article 7.2.7</a></li>
<li><a href="#">Article 7.2.8</a></li>
</ul>
</section>
</div>
<div class="span-2">
<section><h4><a href="#">Section 7.3</a></h4>
<ul>
<li><a href="#">Article 7.3.1</a></li>
<li><a href="#">Article 7.3.2</a></li>
<li><a href="#">Article 7.3.3</a></li>
</ul>
</section>
</div>
<div class="clear"></div>
</div></section></li>
<!-- DataAjaxFragmentEnd -->
</html>